### ISSUE TITLE
Small typo (relvent) in first paragraph of generated A11y statement

### ISSUE THREAD

**Issue by metalandcoffee** [10degrees/accessibility-statement-plugin#3]
After clicking the "Create New Page" button on the Accessibility Settings page, I noticed a typo in the first paragraph of the generated statement. 

![image](https://user-images.githubusercontent.com/20868511/101551737-89c5bf00-397f-11eb-887a-234f052aba68.png)

**Comment by AliceKLWilliams** [comment]
Thanks for pointing this out! I've gone ahead and edited that so it says "relevant" instead.
